### ISSUE TITLE
[BUG:] createContext error

### ISSUE THREAD

**Issue by pomaking** [pdovhomilja/nextcrm-app#33]
### Describe the bug

Getting the following error consistently. I've tried installing locally and through Github codespaces.

Starting...
 ✓ Ready in 4s
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 1274ms (98 modules)
 ○ Compiling /[locale] ...
 ✓ Compiled /[locale] in 16.4s (1630 modules)
 ✓ Compiled in 1373ms (557 modules)
 ⨯ createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/@floating-ui/react/dist/floating-ui.react.esm.js:111:77)
    at (rsc)/./node_modules/@floating-ui/react/dist/floating-ui.react.esm.js (/workspaces/nextcrm-app/.next/server/vendor-chunks/@floating-ui.js:20:1)
    at __webpack_require__ (/workspaces/nextcrm-app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@tremor/react/dist/components/util-elements/Tooltip/Tooltip.js:6:76)
    at (rsc)/./node_modules/@tremor/react/dist/components/util-elements/Tooltip/Tooltip.js (/workspaces/nextcrm-app/.next/server/vendor-chunks/@tremor.js:40:1)
    at __webpack_require__ (/workspaces/nextcrm-app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@tremor/react/dist/components/vis-elements/ProgressBar/ProgressBar.js:8:91)
    at (rsc)/./node_modules/@tremor/react/dist/components/vis-elements/ProgressBar/ProgressBar.js (/workspaces/nextcrm-app/.next/server/vendor-chunks/@tremor.js:50:1)
    at __webpack_require__ (/workspaces/nextcrm-app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/__barrel_optimize__?names=Flex,ProgressBar,Text!=!./node_modules/@tremor/react/dist/index.js:8:109) {
  type: 'TypeError',
  page: '/en'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 8s (1830 modules)
 GET /en 500 in 27199ms

### Steps to reproduce

Followed install instructions on local machine (Ubuntu 20.04) and using Github Codespaces.

### Browsers

Brave

### Additional context (Is this in dev or production?)

dev

**Comment by zhutoutoutousan** [comment]
Turns out, twas in the file storage-quota.tsx, there is a <ProgressBar> in it, so in this file we need to add "use client" in it for it to work

**Comment by pdovhomilja** [comment]
Fixed by @zhutoutoutousan , merged to main.
